### ISSUE TITLE
[bug] 无法删除文件

### ISSUE THREAD

**Issue by Borber** [xausky/DockerRegisterCloud#56]
删除报错, 文件名无误

```shell
Unhandled exception:
Instance of 'PermissionDeniedException'
#0      DrcHttpClient.send (package:docker_register_cloud/helper/DrcHttpClient.dart:70)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:91)
<asynchronous suspension>
#2      Repository.remove.<anonymous closure> (package:docker_register_cloud/repository.dart:119)
<asynchronous suspension>

```

**Comment by xausky** [comment]
没有权限，drc login 先登录，确保输入正确的帐号密码

**Comment by Borber** [comment]
> 没有权限，drc login 先登录，确保输入正确的帐号密码

我确保我是登录了的, 我可以正常 push pull mv 就是 不能 rm

**Comment by xausky** [comment]
> 

方便的话可以私仓库地址和帐号密码以及删除命令到我邮箱

**Comment by Borber** [comment]
> > 
> 
> 方便的话可以私仓库地址和帐号密码以及删除命令到我邮箱

就阿里云的仓库, 几个月前就有这问题了
